### ISSUE TITLE
Try out with authz info

### ISSUE THREAD

**Issue by Mokaffe** [edmunds/redoc-tryout#1]
Hi, How about api that need authz when user want to try it out?

**Comment by wll8** [comment]
@Mokaffe 

Try [redoc-try](https://github.com/wll8/redoc-try), use `swagger Try it out` in` redoc` project.

![re-doc try](https://github.com/wll8/redoc-try/raw/master/redoc_show.png)

**Comment by Mokaffe** [comment]
Thanks.
